/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.*/

public class Euler2 {

	public static void main(String[] args) {
		
		long x = 0;
		long y = 2;
		long z = x+y;
		long sum=0;
		
		while (y < 4000000)
		{
			sum+=z;
			z=4*y+x;//only consider every third number 
			x=y;
			y=z;
		}
		
		System.out.println(sum);
	}

}
 
